### ISSUE TITLE
Hello! Thank you for a very pure and beautiful theme 😜👍

### ISSUE THREAD

**Issue by zhouxinghong** [Bluemoondragon07/Obsidian-Bolt#1]
Hello! Thank you for a very pure and beautiful theme 😜👍

Here I would like to ask you to add an option to allow users to decide whether to show or hide the expand button in the upper left corner, like this:

![image](https://github.com/Bluemoondragon07/Obsidian-Bolt/assets/54253524/68a85e69-ff3d-494a-b24f-9930d7826470)

![image](https://github.com/Bluemoondragon07/Obsidian-Bolt/assets/54253524/069b3e53-9ced-4a89-8fea-b38ca9d24695)

Not having this expand button in the top left is really jarring for people who are used to the default theme behavior.

So I hope you can add an option in the next version to allow users to decide whether to show or hide the expand button in the upper left corner.

Thanks again for a very pure and beautiful theme 😜👍

Windows10
Version 0.0.2
Obsidian 1.37

**Comment by Bluemoondragon07** [comment]
Thank you for your useful feedback. I personally would also like this feature someday, as I prefer the default menu, but I wanted the menu design to be unique for the first version. I will consider this if I ever get back to working on this theme (which I really want to do, but school's been in the way, sadly)! Thank you again for your feedback!

**Comment by Bluemoondragon07** [comment]
This has been added in the latest update. Enjoy!
